version: '3.8'

services:
  app:
    build: ./app
    container_name: app_container
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  nginx:
    build: ./nginx
    container_name: nginx_container
    ports:
      - "80:80"
    depends_on:
      - app

  mongo:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
